---
name: "CI ARM"

# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    paths-ignore:
      - '*.md'

  workflow_dispatch:
    paths-ignore:
      - '*.md'

jobs:
  arm:
    name: "ARM64: ${{ matrix.shell }} on ${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        shell: [bash, zsh]  # Currently no ash
        image: [alpine, debian, archlinux]


    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Install for ${{ matrix.image }}"
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ${{ fromJSON( '{alpine: "alpine_latest", debian: "bullseye", archlinux: "archarm_latest"}' )[matrix.image] }}

          run: |
            case ${{ matrix.image }} in
              alpine) apk update && apk add bash zsh;;
              debian) apt-get update && apt-get install -y busybox zsh && ln -sf /bin/busybox /bin/ash;;
              archlinux) pacman -Sy --noconfirm busybox zsh which && ln -sf /bin/busybox /bin/ash;;
            esac

      - name: Run
        uses: ./.github/actions/test
        with:
          shell: ${{ matrix.shell }}

            #    alpine_arm64:
            #            distro: alpine_latest
            #    debian_arm64:
            #            distro: bullseye
            #    arch_arm64:
            #            distro: archarm_latest
